name: v2
on:
  schedule:
  - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  qiandao:
    runs-on: ubuntu-latest
    name: qiandao

    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: main

    - name: setup
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'
    - run: pip install -r ./requirements.txt && python ./main.py

