name: v2
env:
      USER_ID: ${{ vars.USER_ID }}
      KEY: ${{ vars.KEY }}
      URL: ${{ vars.URL }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
      EMAILS: ${{ vars.EMAILS }}
      MAIL_USER: ${{ vars.MAIL_USER }}
on:
  schedule:
  - cron:  '0 20 * * *'
  workflow_dispatch:

jobs:
  qiandao:
    runs-on: ubuntu-latest
    name: qiandao

    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: main

    - name: setup
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'
    - run: pip install -r ./requirements.txt && python ./main.py
    #- run: pip install -r ./requirements.txt && python ./git/main.py
    
    - name: commit
      run: |
        git config --global user.email 1840628213@qq.com
        git config --global user.name txw
        git add log.txt
        git add ./list
        git commit -m "log" -a
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.TOKEN }}
    
  
        

